# Generated by Django 4.2.1 on 2023-08-15 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maketripsapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='trip',
        ),
    ]
