# Generated by Django 4.2.1 on 2023-08-15 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maketripsapp', '0002_delete_trip'),
    ]

    operations = [
        migrations.CreateModel(
            name='place',
            fields=[
                ('place_name', models.TextField(max_length=50, primary_key=True, serialize=False)),
                ('place_description', models.TextField()),
                ('place_image', models.ImageField(upload_to='places')),
                ('place_image2', models.ImageField(upload_to='places')),
                ('place_image3', models.ImageField(upload_to='places')),
                ('place_image4', models.ImageField(upload_to='places')),
            ],
        ),
    ]
