# Generated by Django 4.2.1 on 2023-08-15 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maketripsapp', '0005_alter_place_place_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='place_description',
            new_name='placedescription',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='place_image',
            new_name='placeimage',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='place_image2',
            new_name='placeimage2',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='place_image3',
            new_name='placeimage3',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='place_image4',
            new_name='placeimage4',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='place_name',
            new_name='placename',
        ),
    ]
