# Generated by Django 4.2.1 on 2023-08-19 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maketripsapp', '0007_myreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myreview',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
