# Generated by Django 4.2.1 on 2023-08-19 09:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maketripsapp', '0010_alter_myreview_review_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myreview',
            name='review_time',
            field=models.DateField(verbose_name=datetime.datetime(2023, 8, 19, 14, 45, 31, 628313)),
        ),
    ]
