# Generated by Django 4.2.1 on 2023-08-21 12:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maketripsapp', '0017_alter_myreview_review_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myreview',
            name='review_time',
            field=models.DateField(default=datetime.datetime(2023, 8, 21, 18, 19, 37, 221525)),
        ),
    ]
