# Generated by Django 4.2.1 on 2023-08-22 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maketripsapp', '0020_alter_myreview_rdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myreview',
            name='rdate',
        ),
    ]
