# Generated by Django 4.2.1 on 2023-08-22 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maketripsapp', '0021_remove_myreview_rdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myreview',
            old_name='review',
            new_name='review_desc',
        ),
    ]
