# Generated by Django 4.2.1 on 2023-08-22 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maketripsapp', '0023_myreviews_delete_myreview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Myreviews',
        ),
    ]
