# Generated by Django 4.2.1 on 2023-08-22 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maketripsapp', '0024_delete_myreviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='Myreviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_place', models.CharField(max_length=50)),
                ('rating_no', models.IntegerField()),
                ('review_desc', models.TextField()),
                ('username', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
