# Generated by Django 4.2.1 on 2023-09-07 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maketripsapp', '0025_myreviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('place_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='maketripsapp.place')),
                ('hotel_name', models.CharField(max_length=50)),
                ('hotel_location', models.CharField(max_length=50)),
                ('hotel_Mainimage', models.ImageField(upload_to='hotels')),
                ('hotel_image1', models.ImageField(upload_to='hotels')),
                ('hotel_image2', models.ImageField(upload_to='hotels')),
                ('hotel_image3', models.ImageField(upload_to='hotels')),
            ],
            bases=('maketripsapp.place',),
        ),
    ]
