# Generated by Django 4.2.1 on 2023-09-07 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maketripsapp', '0026_hotels'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hotels',
        ),
    ]
