# Generated by Django 4.2.1 on 2023-09-08 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maketripsapp', '0030_hotels'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hotels',
        ),
    ]
