# Generated by Django 4.2.1 on 2023-09-13 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maketripsapp', '0032_hotels'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravellerDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.IntegerField()),
                ('h_name', models.CharField(max_length=60)),
                ('T_FirstName', models.CharField(max_length=50)),
                ('T_LastName', models.CharField(max_length=50)),
                ('T_email', models.EmailField(max_length=254)),
                ('T_contactNo', models.CharField(max_length=20)),
                ('T_address', models.CharField(max_length=70)),
                ('room_type', models.CharField(max_length=100)),
                ('days', models.IntegerField()),
                ('T_pincode', models.IntegerField()),
                ('T_country', models.CharField(max_length=50)),
                ('special_req', models.TextField()),
                ('username', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
