# Generated by Django 4.2.5 on 2023-10-31 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maketripsapp', '0036_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='Gallery_place',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='Gallery_place_desc',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='Gallery_img',
            field=models.ImageField(null=True, upload_to='gallery'),
        ),
    ]
