# Generated by Django 4.2.5 on 2023-10-31 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maketripsapp', '0037_gallery_gallery_place_gallery_gallery_place_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='Gallery_img',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
