# Generated by Django 4.2.5 on 2023-11-02 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maketripsapp', '0038_alter_gallery_gallery_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('G_place', models.CharField(max_length=50)),
                ('Gallery_img', models.CharField(max_length=150)),
            ],
        ),
    ]
