# Generated by Django 4.2.5 on 2023-11-11 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maketripsapp', '0039_gallery_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='vacations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v_place', models.CharField(max_length=70)),
                ('v_desc', models.TextField()),
                ('img_link', models.CharField(max_length=150)),
            ],
        ),
    ]
